Build and distribute binaries (#60)

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -31,7 +31,7 @@ jobs:
       - uses: actions/cache@v3
         with:
           path: ~/.conan/data
-          key: ${{ runner.os }}-x86_64
+          key: tests-${{ runner.os }}-x86_64
       - name: Install dependencies
         run: |
           sudo apt update
@@ -54,18 +54,17 @@ jobs:
       - uses: actions/cache@v3
         with:
           path: ~/.conan/data
-          key: ${{ runner.os }}-x86_64
+          key: tests-${{ runner.os }}-x86_64
       - name: Install dependencies
         run: brew install cmake gcovr ninja
       - name: Install Conan
         run: pip3 install "conan<2.0"
-      - name: Configure project (try 1/2)
-        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=undefined" -DWITH_CONAN=ON -DWITH_TESTS=ON
-        continue-on-error: true
-        # For some unknown reasons bison fails to build on GitHub macOS 12 runners.
-        # However, if we call conan twice, it seems to work...¯\(◉‿◉)/¯
-      - name: Configure project (try 2/2)
-        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=undefined" -DWITH_CONAN=ON -DWITH_TESTS=ON
+      # For some unknown reasons bison fails to build on GitHub macOS 12 runners.
+      # However, if we call conan twice, it seems to work...¯\(◉‿◉)/¯
+      - name: Configure project
+        run: |
+          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=undefined" -DWITH_CONAN=ON -DWITH_TESTS=ON || true
+          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage -fsanitize=address -fsanitize=undefined" -DWITH_CONAN=ON -DWITH_TESTS=ON
       - name: Build tests
         run: cmake --build build --target caracal-test
       - name: Run tests
